name: CI/CD Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual running

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up Node.js environment
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: npm i # Some folks recommend 'npm ci', but I don't like the required package lock.

      - name: Run Tests
        run: npm test # Executes the 'test' script defined in your package.json
